# yaml 配置
version: "3.7"
services:
  redis:
    image: "redis:8.0"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "325523"
      MYSQL_DATABASE: "agricultural_vision"
      MYSQL_PASSWORD: "325523"
    volumes:
      - ./init.sql:/data/application/init.sql
  agricultural_vision:
    build: .
    command: sh -c "./wait-for.sh redis:6379 mysql:3306 -- ./agricultural_vision ./conf/config.yaml"
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"