services:
  redis:
    image: "redis:8.0"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password", "--bind-address=0.0.0.0", "--init-file=/docker-entrypoint-initdb.d/init.sql" ]
    environment:
      MYSQL_ROOT_PASSWORD: "325523"
      MYSQL_DATABASE: "agricultural_vision"
      MYSQL_ROOT_HOST: "%"  # 允许root从任何主机连接
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p325523" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  agricultural_vision:
    build: .
    command: sh -c "/app/wait-for.sh redis:6379 mysql:3306 -- /app/agricultural_vision /app/conf/config.yaml"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge