apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: agricultural-vision
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:4.0
          ports:
            - name: client
              containerPort: 9092
              protocol: TCP
            - name: controller
              containerPort: 9093
              protocol: TCP
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-headless.agricultural-vision.svc.cluster.local:9093"  # 单节点示例
            - name: KAFKA_CFG_LISTENERS
              value: "CONTROLLER://:9093,PLAINTEXT://:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"  # 新增这一行
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(hostname -s).kafka-headless.agricultural-vision.svc.cluster.local:9092"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"  # 单节点场景设为 1
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: TZ
              value: "Asia/Shanghai"
      volumes:
        - name: data
          emptyDir: {}  # 开发环境使用临时存储，避免 PVC 问题
  volumeClaimTemplates: []  # 移除 PVC 依赖
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: agricultural-vision
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-client
  namespace: agricultural-vision
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
  type: ClusterIP