apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: agricultural-vision
data:
  init.sql: |
    -- 你的 init.sql 内容
    CREATE DATABASE IF NOT EXISTS agricultural_vision;
    USE agricultural_vision;
    
    -- 在这里添加你的表结构和初始数据
    -- 例如：
    -- CREATE TABLE IF NOT EXISTS users (...);