apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: agricultural-vision
  labels:
    app: mysql
spec:
  type: ClusterIP
  clusterIP: None  # 无头服务，用于稳定的Pod网络标识
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: agricultural-vision
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: agricultural-vision
spec:
  serviceName: "mysql-headless"  # 关联无头服务
  replicas: 2  # 初始为2个副本，可扩展
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: agricultural_vision
            - name: MYSQL_ROOT_HOST
              value: "%"
          args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
            - --bind-address=0.0.0.0
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p$(MYSQL_ROOT_PASSWORD)
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p$(MYSQL_ROOT_PASSWORD)
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-init-script
  volumeClaimTemplates:  # 自动创建PVC
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: agricultural-vision
data:
  init.sql: |
    -- 创建数据库（如果不存在）
    CREATE DATABASE IF NOT EXISTS agricultural_vision;
    
    -- 使用数据库
    USE agricultural_vision;
    
    -- 创建允许从任何主机连接的root用户
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '325523';
    
    -- 授予所有权限
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    
    -- 刷新权限
    FLUSH PRIVILEGES;