apiVersion: apps/v1
kind: Deployment
metadata:
  name: agricultural-vision
  namespace: agricultural-vision
  labels:
    app: agricultural-vision
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agricultural-vision
  template:
    metadata:
      labels:
        app: agricultural-vision
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql-service 3306; do
                echo "Waiting for MySQL..."
                sleep 2
              done
              echo "MySQL is ready!"
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z redis-service 6379; do
                echo "Waiting for Redis..."
                sleep 2
              done
              echo "Redis is ready!"
      containers:
        - name: agricultural-vision
          image: agricultural-vision:latest  # 需要替换为你的实际镜像地址
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GIN_MODE
              value: "release"
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /app/conf
              readOnly: true
          command: ["./agricultural_vision"]
          args: ["conf/config.yaml"]
      volumes:
        - name: config
          configMap:
            name: agricultural-vision-config