apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: agricultural-vision
  labels:
    app: etcd
spec:
  ports:
    - port: 2379  # 客户端端口（供应用连接）
      name: client
      targetPort: 2379
    - port: 2380  # 节点间通信端口
      name: peer
      targetPort: 2380
  clusterIP: None  # 无头服务，用于 StatefulSet 节点间通信
  selector:
    app: etcd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: agricultural-vision
spec:
  serviceName: etcd-service  # 关联无头服务
  replicas: 3  # 建议奇数副本（1/3/5），确保选举一致性
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:latest
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"  # 开发环境使用，生产环境需启用认证
            - name: ETCD_ADVERTISE_CLIENT_URLS  # 客户端访问地址（关键修复）
              value: "http://$(ETCD_NAME).$( SERVICE_NAME ).$( NAMESPACE ).svc.cluster.local:2379"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS  # 节点间通信地址（关键修复）
              value: "http://$(ETCD_NAME).$( SERVICE_NAME ).$( NAMESPACE ).svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER  # 集群初始化列表（自动生成节点名）
              value: "etcd-0=http://etcd-0.etcd-service.agricultural-vision.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-service.agricultural-vision.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-service.agricultural-vision.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"  # 首次启动用 new，后续扩容用 existing
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"  # 监听所有 IP
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"  # 监听所有 IP
            - name: ETCD_NAME  # 自动获取 Pod 名称（如 etcd-0）
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: etcd-data
              mountPath: /bitnami/etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi  # 按需调整存储大小
        storageClassName: "standard"  # 指定存储类，若无默认需显式声明