apiVersion: v1
kind: ConfigMap
metadata:
  name: agricultural-vision-config
  namespace: agricultural-vision
data:
  config.yaml: |
    name: "agricultural vision"
    mode: "release"
    port: 8080
    version: "v0.0.1"
    start_time: "2025-01-14"
    machine_id: 1
    
    # JWT配置 - 使用环境变量
    jwt:
      secret: "${JWT_SECRET}"
      issuer: "shawn"
      access_expire_hours: 168
      refresh_expire_hours: 8760
    
    log:
      level: "info"
      filename: "/var/log/agricultural_vision.log"
      max_size: 1000
      max_age: 3600
      max_backups: 5
    
    mysql:
      host: "mysql"
      port: 3306
      user: "root"
      password: "${MYSQL_PASSWORD}"
      db: "agricultural_vision"
      max_open_conns: 100
      max_idle_conns: 20
    
    redis:
      host: "redis"
      password: ""
      port: 6379
      db: 0
      pool_size: 100
      min_idle_conns: 50
    
    ai:
      system_content1: "你是一位古代农学大家..."
      system_content2: "你是一个农业全景知识库..."
      system_content3: "你专注于中国传统二十四节气..."
      system_content4: "你聚焦各地农业风貌..."
      api_key: "${AI_API_KEY}"
      api_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
      model: "charglm-4"
    
    alioss:
      endpoint: "oss-cn-beijing.aliyuncs.com"
      access_key_id: "${OSS_ACCESS_KEY_ID}"
      access_key_secret: "${OSS_ACCESS_KEY_SECRET}"
      bucket_name: "agricultural-vision"
      user_avatar_path: "user_avatar/"
      post_image_path: "post_image/"